services:
  postgres:
    restart: unless-stopped
    env_file:
      - .env.production
    ports: []

  app-blue:
    image: jotaemege/sportsclub-app:latest
    restart: unless-stopped
    env_file:
      - .env.production
    ports: []

  app-green:
    image: jotaemege/sportsclub-app:latest
    restart: unless-stopped
    env_file:
      - .env.production
    ports: []

  nginx:
    restart: unless-stopped
    ports:
      - "80:80"