services:
  postgres:
    restart: unless-stopped
    env_file:
      - .env.production
    ports: []

  app-blue:
    #image: ${DOCKER_USERNAME}/sportsclub:latest
    restart: unless-stopped
    env_file:
      - .env.production
    ports: []

  app-green:
    #image: ${DOCKER_USERNAME}/sportsclub:latest
    restart: unless-stopped
    env_file:
      - .env.production
    ports: []

  nginx:
    restart: unless-stopped
    ports:
      - "80:80"