services:
  postgres:
    #image: ${DOCKER_USERNAME}/sportsclub:latest
    restart: unless-stopped
    env_file:
      - .env.production
    ports: []

  app:
    restart: unless-stopped
    env_file:
      - .env.production
    ports: []

  nginx:
    restart: unless-stopped
    ports:
      - "8080:80"